### ISSUE TITLE
TAPi18n not ready in useraccounts-configuration.js

### ISSUE THREAD

**Issue by fknipp** [meteor/todos#104]
In https://github.com/meteor/todos/blob/master/imports/startup/client/useraccounts-configuration.js some texts are configured using `TAPi18n.__()`. These texts are not reactive, thus changing the language does not change texts.

Even a `TAPi18n.setLanguage()` right before wouldn't help, as `TAPi18n.setLanguage()` creates a jQuery Deferred and returns immediately. Putting the call to `AccountTemplates.configure()` in the `.done()` would help, but I put the internationalization stuff into its own file, which is loaded before. I don't want to wait there to minimize delays of the client startup.

Maybe there's a better approach.

I just wanted to point out, that the usage of `TAPi18n` in the mentioned file promises a feature, which wouldn't work as expected.

**Comment by hwillson** [comment]
You could consider wrapping your entire `AccountTemplates.configure` call in a `Tracker.autorun`, so that when the language changes via a `TAPi18n.setLanguage` call, the translation calls defined in the `configure` object are re-run. This will only work by leveraging part of the `useraccounts` internal API however, since by default you can't call `AccountTemplates.configure` a second time, after it has already been initialized. Here's an example of how this could work:

```
Tracker.autorun(() => {
  AccountTemplates._initialized = false;
  AccountTemplates.configure({
    ...
  });
});
```

Setting `_initialized` to false will let you call `configure` multiple times.

All of the above being said, I don't recommend heading down this path. This is a hack - using `_initialized` means you're tying yourself to the `useraccounts` internals. A better option in this case is to get rid of all TAPi18n calls that are part of the `AccountTemplates.configure` configuration object, and instead rely on the `useraccounts` translations that already exist in the [softwarerero:accounts-t9n](https://atmospherejs.com/softwarerero/accounts-t9n) package. This package will automatically take care of translating all `useraccounts` strings, that are part of the default templates.

I've submitted a PR (#184) to update the todos app with a more encompassing i18n demonstration. This includes leveraging `accounts-t9n` for `useraccounts` translations, as well as:

- Making sure the entire application is i18n ready (all language related strings have been moved into i18n files, extracted from both the client and server).
- Demonstrating a full second language (using French).
- Wired up a sample language toggle.

I'll get this PR merged shortly (then look into doing something similar for the react branch). Thanks!

**Comment by fknipp** [comment]
Hi @hwillson, thanks for providing the hints about `_initialized` (which I'm not going to use) and the PR.

**Comment by hwillson** [comment]
Just for reference - I've updated the `react` branch to show a full working i18n implementation using `universe:i18n`. Closing this off.
