### ISSUE TITLE
Implement full i18n when we've integrated 1.3

### ISSUE THREAD

**Issue by tmeasday** [meteor/todos#59]
Right now we have [a POC](https://github.com/meteor/todos/pull/41) i18n against the 1.2 codebase (i.e. the all-package approach).

It's sort of fiddly and requires putting control files in every package that needs i18n. We think it will be significantly easier in 1.3 when we can use modules and don't need to take the all-package approach. So we'll put off implementing full i18n until then.

**Comment by zayaisshawn** [comment]
yaay!!

**Comment by tmeasday** [comment]
@stubailo - first pass at this. Some notes:

1. I've just created a single `i18n/en.i18n.json`, rather than placing translations next to the files. Do you think this is wrong? I suspect people tend to pass a big file off to translators all at once.

2. I've not added translations of all the various UI strings, relying on the fact that the lib will just use the key in such cases. I think this is OK, unless we want to modularize UI translations but I'm not sure how if/how people do this?

3. A few things in the accounts UI aren't set by us. e.g. "Forgot Password?" Do you think we can just not worry about this?

4. Shall we create a translation? Maybe you could do one in Ukranian ;)

**Comment by stubailo** [comment]
1. That sounds perfect! I think translations are one thing people love to keep in one place. We should think about what this means for testing UI components though - does it mean they become coupled to your translation files? It seems like the solution would be (1) write your tests against the i18n keys or (2) inject special test translations for all the tests.
2. This is probably fine.
3. I think `useraccounts` has i18n support - I should figure out how to set it up.
4. Sounds like a great idea! I think something more common like Spanish would be best. Or maybe Mandarin, since it's more different? I think we have a few people at the office that speak Mandarin.

**Comment by tmeasday** [comment]
Done. Let's worry about an actual translation later (PRs encouraged!)
